------@diagnostic disable-next-line: undefined-global
---local hs = hs
---
---local M = {}
---
---local ks = function(mod, key)
---	hs.eventtap.keyStroke(mod, key, 0)
---end
---
---local hotkeys = {}
---
----- helper: unbind previous hotkeys
---local function clearHotkeys()
---	for _, hk in ipairs(hotkeys) do
---		hk:delete()
---	end
---	hotkeys = {}
---end
---
----- helper: get number of desktops via AppleScript
---local function getDesktopCount()
---	local script = [[
---        tell application "System Events"
---            tell spaces of mission control preferences
---                count of spaces
---            end tell
---        end tell
---    ]]
---	local ok, result = hs.osascript.applescript(script)
---	if ok then
---		return tonumber(result) or 0
---	end
---	return 0
---end
---
----- bind hotkeys for current desktops
---local function bindHotkeys()
---	clearHotkeys()
---	local count = getDesktopCount()
---	if count == 0 then
---		count = 6
---	end
---	for i = 1, count do
---		local hk = hs.hotkey.bind({ "cmd" }, tostring(i), function()
---			ks({ "ctrl" }, tostring(i))
---		end)
---		table.insert(hotkeys, hk)
---	end
---end
---
---function M.init()
---	bindHotkeys()
---	-- optional: refresh every 5s in case desktops are added/removed
---	hs.timer.doEvery(5, bindHotkeys)
---end
---
---return M
